/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.demo.streams.models;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class GoodWindow extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 4307951139639118475L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"GoodWindow\",\"namespace\":\"com.demo.streams.models\",\"fields\":[{\"name\":\"deviceStatus\",\"type\":\"string\"},{\"name\":\"lastWindow\",\"type\":\"long\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<GoodWindow> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<GoodWindow> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<GoodWindow> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<GoodWindow> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<GoodWindow> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this GoodWindow to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a GoodWindow from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a GoodWindow instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static GoodWindow fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence deviceStatus;
  private long lastWindow;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public GoodWindow() {}

  /**
   * All-args constructor.
   * @param deviceStatus The new value for deviceStatus
   * @param lastWindow The new value for lastWindow
   */
  public GoodWindow(java.lang.CharSequence deviceStatus, java.lang.Long lastWindow) {
    this.deviceStatus = deviceStatus;
    this.lastWindow = lastWindow;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return deviceStatus;
    case 1: return lastWindow;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: deviceStatus = (java.lang.CharSequence)value$; break;
    case 1: lastWindow = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'deviceStatus' field.
   * @return The value of the 'deviceStatus' field.
   */
  public java.lang.CharSequence getDeviceStatus() {
    return deviceStatus;
  }


  /**
   * Sets the value of the 'deviceStatus' field.
   * @param value the value to set.
   */
  public void setDeviceStatus(java.lang.CharSequence value) {
    this.deviceStatus = value;
  }

  /**
   * Gets the value of the 'lastWindow' field.
   * @return The value of the 'lastWindow' field.
   */
  public long getLastWindow() {
    return lastWindow;
  }


  /**
   * Sets the value of the 'lastWindow' field.
   * @param value the value to set.
   */
  public void setLastWindow(long value) {
    this.lastWindow = value;
  }

  /**
   * Creates a new GoodWindow RecordBuilder.
   * @return A new GoodWindow RecordBuilder
   */
  public static com.demo.streams.models.GoodWindow.Builder newBuilder() {
    return new com.demo.streams.models.GoodWindow.Builder();
  }

  /**
   * Creates a new GoodWindow RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new GoodWindow RecordBuilder
   */
  public static com.demo.streams.models.GoodWindow.Builder newBuilder(com.demo.streams.models.GoodWindow.Builder other) {
    if (other == null) {
      return new com.demo.streams.models.GoodWindow.Builder();
    } else {
      return new com.demo.streams.models.GoodWindow.Builder(other);
    }
  }

  /**
   * Creates a new GoodWindow RecordBuilder by copying an existing GoodWindow instance.
   * @param other The existing instance to copy.
   * @return A new GoodWindow RecordBuilder
   */
  public static com.demo.streams.models.GoodWindow.Builder newBuilder(com.demo.streams.models.GoodWindow other) {
    if (other == null) {
      return new com.demo.streams.models.GoodWindow.Builder();
    } else {
      return new com.demo.streams.models.GoodWindow.Builder(other);
    }
  }

  /**
   * RecordBuilder for GoodWindow instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<GoodWindow>
    implements org.apache.avro.data.RecordBuilder<GoodWindow> {

    private java.lang.CharSequence deviceStatus;
    private long lastWindow;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.demo.streams.models.GoodWindow.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.deviceStatus)) {
        this.deviceStatus = data().deepCopy(fields()[0].schema(), other.deviceStatus);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.lastWindow)) {
        this.lastWindow = data().deepCopy(fields()[1].schema(), other.lastWindow);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing GoodWindow instance
     * @param other The existing instance to copy.
     */
    private Builder(com.demo.streams.models.GoodWindow other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.deviceStatus)) {
        this.deviceStatus = data().deepCopy(fields()[0].schema(), other.deviceStatus);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.lastWindow)) {
        this.lastWindow = data().deepCopy(fields()[1].schema(), other.lastWindow);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'deviceStatus' field.
      * @return The value.
      */
    public java.lang.CharSequence getDeviceStatus() {
      return deviceStatus;
    }


    /**
      * Sets the value of the 'deviceStatus' field.
      * @param value The value of 'deviceStatus'.
      * @return This builder.
      */
    public com.demo.streams.models.GoodWindow.Builder setDeviceStatus(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.deviceStatus = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'deviceStatus' field has been set.
      * @return True if the 'deviceStatus' field has been set, false otherwise.
      */
    public boolean hasDeviceStatus() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'deviceStatus' field.
      * @return This builder.
      */
    public com.demo.streams.models.GoodWindow.Builder clearDeviceStatus() {
      deviceStatus = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'lastWindow' field.
      * @return The value.
      */
    public long getLastWindow() {
      return lastWindow;
    }


    /**
      * Sets the value of the 'lastWindow' field.
      * @param value The value of 'lastWindow'.
      * @return This builder.
      */
    public com.demo.streams.models.GoodWindow.Builder setLastWindow(long value) {
      validate(fields()[1], value);
      this.lastWindow = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'lastWindow' field has been set.
      * @return True if the 'lastWindow' field has been set, false otherwise.
      */
    public boolean hasLastWindow() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'lastWindow' field.
      * @return This builder.
      */
    public com.demo.streams.models.GoodWindow.Builder clearLastWindow() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public GoodWindow build() {
      try {
        GoodWindow record = new GoodWindow();
        record.deviceStatus = fieldSetFlags()[0] ? this.deviceStatus : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.lastWindow = fieldSetFlags()[1] ? this.lastWindow : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<GoodWindow>
    WRITER$ = (org.apache.avro.io.DatumWriter<GoodWindow>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<GoodWindow>
    READER$ = (org.apache.avro.io.DatumReader<GoodWindow>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.deviceStatus);

    out.writeLong(this.lastWindow);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.deviceStatus = in.readString(this.deviceStatus instanceof Utf8 ? (Utf8)this.deviceStatus : null);

      this.lastWindow = in.readLong();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.deviceStatus = in.readString(this.deviceStatus instanceof Utf8 ? (Utf8)this.deviceStatus : null);
          break;

        case 1:
          this.lastWindow = in.readLong();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










